/*
 * This file is a part of tdlib-utils
 * Copyright © 2014 (tgx-android@pm.me)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:JvmName("Td")
@file:JvmMultifileClass

package tgx.td

import me.vkryl.annotation.Autogenerated
import org.drinkless.tdlib.TdApi.*

// Cause compilation error whenever new constructor is added to the TDLib type
// by calling one of the corresponding stub methods below in places, where you expect to support all of them.

// CreationDate
// Profitability
// Revenue
@Autogenerated fun assertAffiliateProgramSortOrder_1dd76397 (): AffiliateProgramSortOrder? = null

// Bot
// Channel
// CurrentUser
@Autogenerated fun assertAffiliateType_61cafd43 (): AffiliateType? = null

// Call
// FirebaseAndroid
// FirebaseIos
// FlashCall
// Fragment
// MissedCall
// Sms
// SmsPhrase
// SmsWord
// TelegramMessage
@Autogenerated fun assertAuthenticationCodeType_6b7089f4 (): AuthenticationCodeType? = null

// Closed
// Closing
// LoggingOut
// Ready
// WaitCode
// WaitEmailAddress
// WaitEmailCode
// WaitOtherDeviceConfirmation
// WaitPassword
// WaitPhoneNumber
// WaitPremiumPurchase
// WaitRegistration
// WaitTdlibParameters
@Autogenerated fun assertAuthorizationState_ba756b5f (): AuthorizationState? = null

// ChannelChats
// Chat
// GroupChats
// PrivateChats
@Autogenerated fun assertAutosaveSettingsScope_8e19c065 (): AutosaveSettingsScope? = null

// FreeformGradient
// Gradient
// Solid
@Autogenerated fun assertBackgroundFill_6086fe10 (): BackgroundFill? = null

// ChatTheme
// Fill
// Pattern
// Wallpaper
@Autogenerated fun assertBackgroundType_eedb1e16 (): BackgroundType? = null

// Main
// Stories
@Autogenerated fun assertBlockList_bbade95a (): BlockList? = null

// AllChatAdministrators
// AllGroupChats
// AllPrivateChats
// Chat
// ChatAdministrators
// ChatMember
// Default
@Autogenerated fun assertBotCommandScope_fd010640 (): BotCommandScope? = null

// AcceptedRequest
// AddedToAttachmentMenu
// ConnectedWebsite
// LaunchedWebApp
@Autogenerated fun assertBotWriteAccessAllowReason_d7597302 (): BotWriteAccessAllowReason? = null

// Always
// Custom
// OutsideOfOpeningHours
@Autogenerated fun assertBusinessAwayMessageSchedule_5e55d638 (): BusinessAwayMessageSchedule? = null

// AccountLinks
// AwayMessage
// Bots
// ChatFolderTags
// EmojiStatus
// GreetingMessage
// Location
// OpeningHours
// QuickReplies
// StartPage
// UpgradedStories
@Autogenerated fun assertBusinessFeature_ffe6c6a8 (): BusinessFeature? = null

// Declined
// Disconnected
// Empty
// HungUp
// Missed
// UpgradeToGroupCall
@Autogenerated fun assertCallDiscardReason_241d03d4 (): CallDiscardReason? = null

// DistortedSpeech
// DistortedVideo
// Dropped
// Echo
// Interruptions
// Noise
// PixelatedVideo
// SilentLocal
// SilentRemote
@Autogenerated fun assertCallProblem_181dbc7b (): CallProblem? = null

// TelegramReflector
// Webrtc
@Autogenerated fun assertCallServerType_569fa9f7 (): CallServerType? = null

// Discarded
// Error
// ExchangingKeys
// HangingUp
// Pending
// Ready
@Autogenerated fun assertCallState_2604589b (): CallState? = null

// Data
// DataWithPassword
// Game
@Autogenerated fun assertCallbackQueryPayload_3b0abf6 (): CallbackQueryPayload? = null

// ActiveStoryLimitExceeded
// BoostNeeded
// MonthlyLimitExceeded
// Ok
// PremiumNeeded
// WeeklyLimitExceeded
@Autogenerated fun assertCanPostStoryResult_39d8ac70 (): CanPostStoryResult? = null

// Ok
// UserHasPaidMessages
// UserIsDeleted
// UserRestrictsNewChats
@Autogenerated fun assertCanSendMessageToUserResult_15fb1d0f (): CanSendMessageToUserResult? = null

// Ok
// PasswordNeeded
// PasswordTooFresh
// SessionTooFresh
@Autogenerated fun assertCanTransferOwnershipResult_ac091006 (): CanTransferOwnershipResult? = null

// Cancel
// ChoosingContact
// ChoosingLocation
// ChoosingSticker
// RecordingVideo
// RecordingVideoNote
// RecordingVoiceNote
// StartPlayingGame
// Typing
// UploadingDocument
// UploadingPhoto
// UploadingVideo
// UploadingVideoNote
// UploadingVoiceNote
// WatchingAnimations
@Autogenerated fun assertChatAction_e6a90de7 (): ChatAction? = null

// AddContact
// InviteMembers
// JoinRequest
// ReportAddBlock
// ReportSpam
// SharePhoneNumber
@Autogenerated fun assertChatActionBar_eedc82ed (): ChatActionBar? = null

// All
// Some
@Autogenerated fun assertChatAvailableReactions_21c76ded (): ChatAvailableReactions? = null

// GiftCode
// Giveaway
// Premium
@Autogenerated fun assertChatBoostSource_3dac7dee (): ChatBoostSource? = null

// ChatEventAccentColorChanged
// ChatEventActiveUsernamesChanged
// ChatEventAutomaticTranslationToggled
// ChatEventAvailableReactionsChanged
// ChatEventBackgroundChanged
// ChatEventCustomEmojiStickerSetChanged
// ChatEventDescriptionChanged
// ChatEventEmojiStatusChanged
// ChatEventForumTopicCreated
// ChatEventForumTopicDeleted
// ChatEventForumTopicEdited
// ChatEventForumTopicPinned
// ChatEventForumTopicToggleIsClosed
// ChatEventForumTopicToggleIsHidden
// ChatEventHasAggressiveAntiSpamEnabledToggled
// ChatEventHasProtectedContentToggled
// ChatEventInviteLinkDeleted
// ChatEventInviteLinkEdited
// ChatEventInviteLinkRevoked
// ChatEventInvitesToggled
// ChatEventIsAllHistoryAvailableToggled
// ChatEventIsForumToggled
// ChatEventLinkedChatChanged
// ChatEventLocationChanged
// ChatEventMemberInvited
// ChatEventMemberJoined
// ChatEventMemberJoinedByInviteLink
// ChatEventMemberJoinedByRequest
// ChatEventMemberLeft
// ChatEventMemberPromoted
// ChatEventMemberRestricted
// ChatEventMemberSubscriptionExtended
// ChatEventMessageAutoDeleteTimeChanged
// ChatEventMessageDeleted
// ChatEventMessageEdited
// ChatEventMessagePinned
// ChatEventMessageUnpinned
// ChatEventPermissionsChanged
// ChatEventPhotoChanged
// ChatEventPollStopped
// ChatEventProfileAccentColorChanged
// ChatEventShowMessageSenderToggled
// ChatEventSignMessagesToggled
// ChatEventSlowModeDelayChanged
// ChatEventStickerSetChanged
// ChatEventTitleChanged
// ChatEventUsernameChanged
// ChatEventVideoChatCreated
// ChatEventVideoChatEnded
// ChatEventVideoChatMuteNewParticipantsToggled
// ChatEventVideoChatParticipantIsMutedToggled
// ChatEventVideoChatParticipantVolumeLevelChanged
@Autogenerated fun assertChatEventAction_53b6b01e (): ChatEventAction? = null

// Archive
// Folder
// Main
@Autogenerated fun assertChatList_db6c93ab (): ChatList? = null

// Administrator
// Banned
// Creator
// Left
// Member
// Restricted
@Autogenerated fun assertChatMemberStatus_33fc5755 (): ChatMemberStatus? = null

// Administrators
// Banned
// Bots
// Contacts
// Members
// Mention
// Restricted
@Autogenerated fun assertChatMembersFilter_2127467 (): ChatMembersFilter? = null

// CustomEmoji
// RegularOrMask
@Autogenerated fun assertChatPhotoStickerType_b827816a (): ChatPhotoStickerType? = null

// Earnings
// Refund
// Withdrawal
@Autogenerated fun assertChatRevenueTransactionType_2bf38aa5 (): ChatRevenueTransactionType? = null

// MtprotoProxy
// PublicServiceAnnouncement
@Autogenerated fun assertChatSource_12b21238 (): ChatSource? = null

// Channel
// Supergroup
@Autogenerated fun assertChatStatistics_6744ad70 (): ChatStatistics? = null

// Message
// Story
@Autogenerated fun assertChatStatisticsObjectType_5cb871fe (): ChatStatisticsObjectType? = null

// BasicGroup
// Private
// Secret
// Supergroup
@Autogenerated fun assertChatType_e562ec7d (): ChatType? = null

// Ok
// PublicChatsTooMany
// PublicGroupsUnavailable
// UsernameInvalid
// UsernameOccupied
// UsernamePurchasable
@Autogenerated fun assertCheckChatUsernameResult_936bb8da (): CheckChatUsernameResult? = null

// NameInvalid
// NameOccupied
// Ok
@Autogenerated fun assertCheckStickerSetNameResult_98a5b530 (): CheckStickerSetNameResult? = null

// PhoneNumber
// Username
@Autogenerated fun assertCollectibleItemType_39fde42a (): CollectibleItemType? = null

// Connecting
// ConnectingToProxy
// Ready
// Updating
// WaitingForNetwork
@Autogenerated fun assertConnectionState_963d6b5f (): ConnectionState? = null

// ApplePush
// ApplePushVoIP
// BlackBerryPush
// FirebaseCloudMessaging
// HuaweiPush
// MicrosoftPush
// MicrosoftPushVoIP
// SimplePush
// TizenPush
// UbuntuPush
// WebPush
// WindowsPush
@Autogenerated fun assertDeviceToken_de4a4f61 (): DeviceToken? = null

// Regular
// SlotMachine
@Autogenerated fun assertDiceStickers_bd2aa513 (): DiceStickers? = null

// AppleId
// Code
// GoogleId
@Autogenerated fun assertEmailAddressAuthentication_8ae3c935 (): EmailAddressAuthentication? = null

// Available
// Pending
@Autogenerated fun assertEmailAddressResetState_c8e4d9f5 (): EmailAddressResetState? = null

// Premium
// Search
@Autogenerated fun assertEmojiCategorySource_d5234ae8 (): EmojiCategorySource? = null

// ChatPhoto
// Default
// EmojiStatus
// RegularStickers
@Autogenerated fun assertEmojiCategoryType_710c6ccb (): EmojiCategoryType? = null

// CustomEmoji
// UpgradedGift
@Autogenerated fun assertEmojiStatusType_acfd58c8 (): EmojiStatusType? = null

// Animation
// Audio
// Document
// None
// NotificationSound
// Photo
// PhotoStory
// ProfilePhoto
// Secret
// SecretThumbnail
// Secure
// SelfDestructingPhoto
// SelfDestructingVideo
// SelfDestructingVideoNote
// SelfDestructingVoiceNote
// Sticker
// Thumbnail
// Unknown
// Video
// VideoNote
// VideoStory
// VoiceNote
// Wallpaper
@Autogenerated fun assertFileType_8b700691 (): FileType? = null

// Android
// Ios
@Autogenerated fun assertFirebaseAuthenticationSettings_ffcd127a (): FirebaseAuthenticationSettings? = null

// PlayIntegrity
// SafetyNet
@Autogenerated fun assertFirebaseDeviceVerificationParameters_21a9fc9c (): FirebaseDeviceVerificationParameters? = null

// Number
// Price
// PriceChangeDate
@Autogenerated fun assertGiftForResaleOrder_8b9dfb69 (): GiftForResaleOrder? = null

// Completed
// Ongoing
@Autogenerated fun assertGiveawayInfo_cee9b325 (): GiveawayInfo? = null

// Administrator
// AlreadyWasMember
// DisallowedCountry
// Eligible
// Participating
@Autogenerated fun assertGiveawayParticipantStatus_18551e87 (): GiveawayParticipantStatus? = null

// Premium
// Stars
@Autogenerated fun assertGiveawayPrize_28ff2954 (): GiveawayPrize? = null

// Main
// ScreenSharing
@Autogenerated fun assertGroupCallDataChannel_28a91fa3 (): GroupCallDataChannel? = null

// Full
// Medium
// Thumbnail
@Autogenerated fun assertGroupCallVideoQuality_68d0c33e (): GroupCallVideoQuality? = null

// Buy
// Callback
// CallbackGame
// CallbackWithPassword
// CopyText
// LoginUrl
// SwitchInline
// Url
// User
// WebApp
@Autogenerated fun assertInlineKeyboardButtonType_4c981aa8 (): InlineKeyboardButtonType? = null

// Animation
// Article
// Audio
// Contact
// Document
// Game
// Location
// Photo
// Sticker
// Venue
// Video
// VoiceNote
@Autogenerated fun assertInlineQueryResult_6a8a1449 (): InlineQueryResult? = null

// StartBot
// WebApp
@Autogenerated fun assertInlineQueryResultsButtonType_7d3d015d (): InlineQueryResultsButtonType? = null

// Local
// Previous
// Remote
@Autogenerated fun assertInputBackground_287c144c (): InputBackground? = null

// Animation
// Previous
// Static
// Sticker
@Autogenerated fun assertInputChatPhoto_fb548ada (): InputChatPhoto? = null

// ApplePay
// GooglePay
// New
// Saved
@Autogenerated fun assertInputCredentials_cb4d5ebc (): InputCredentials? = null

// Generated
// Id
// Local
// Remote
@Autogenerated fun assertInputFile_ea011173 (): InputFile? = null

// Link
// Message
@Autogenerated fun assertInputGroupCall_e13f7123 (): InputGroupCall? = null

// Animation
// Article
// Audio
// Contact
// Document
// Game
// Location
// Photo
// Sticker
// Venue
// Video
// VoiceNote
@Autogenerated fun assertInputInlineQueryResult_c2856322 (): InputInlineQueryResult? = null

// Message
// Name
// Telegram
@Autogenerated fun assertInputInvoice_98c544d7 (): InputInvoice? = null

// InputMessageAnimation
// InputMessageAudio
// InputMessageContact
// InputMessageDice
// InputMessageDocument
// InputMessageForwarded
// InputMessageGame
// InputMessageInvoice
// InputMessageLocation
// InputMessagePaidMedia
// InputMessagePhoto
// InputMessagePoll
// InputMessageSticker
// InputMessageStory
// InputMessageText
// InputMessageVenue
// InputMessageVideo
// InputMessageVideoNote
// InputMessageVoiceNote
@Autogenerated fun assertInputMessageContent_6d335c (): InputMessageContent? = null

// ExternalMessage
// Message
// Story
@Autogenerated fun assertInputMessageReplyTo_acef6f3a (): InputMessageReplyTo? = null

// Photo
// Video
@Autogenerated fun assertInputPaidMediaType_7f9deae6 (): InputPaidMediaType? = null

// Address
// BankStatement
// DriverLicense
// EmailAddress
// IdentityCard
// InternalPassport
// Passport
// PassportRegistration
// PersonalDetails
// PhoneNumber
// RentalAgreement
// TemporaryRegistration
// UtilityBill
@Autogenerated fun assertInputPassportElement_d81b9316 (): InputPassportElement? = null

// DataField
// File
// Files
// FrontSide
// ReverseSide
// Selfie
// TranslationFile
// TranslationFiles
// Unspecified
@Autogenerated fun assertInputPassportElementErrorSource_80bdb667 (): InputPassportElementErrorSource? = null

// FoundVenue
// Link
// Location
// Message
// PreviousVenue
// SuggestedReaction
// UpgradedGift
// Weather
@Autogenerated fun assertInputStoryAreaType_e88e9665 (): InputStoryAreaType? = null

// Photo
// Video
@Autogenerated fun assertInputStoryContent_6b57a59a (): InputStoryContent? = null

// ActiveSessions
// AttachmentMenuBot
// AuthenticationCode
// Background
// BotAddToChannel
// BotStart
// BotStartInGroup
// BusinessChat
// BuyStars
// ChangePhoneNumber
// ChatAffiliateProgram
// ChatBoost
// ChatFolderInvite
// ChatFolderSettings
// ChatInvite
// DefaultMessageAutoDeleteTimerSettings
// EditProfileSettings
// Game
// GroupCall
// InstantView
// Invoice
// LanguagePack
// LanguageSettings
// MainWebApp
// Message
// MessageDraft
// MyStars
// PassportDataRequest
// PhoneNumberConfirmation
// PremiumFeatures
// PremiumGift
// PremiumGiftCode
// PrivacyAndSecuritySettings
// Proxy
// PublicChat
// QrCodeAuthentication
// RestorePurchases
// Settings
// StickerSet
// Story
// Theme
// ThemeSettings
// UnknownDeepLink
// UnsupportedProxy
// UpgradedGift
// UserPhoneNumber
// UserToken
// VideoChat
// WebApp
@Autogenerated fun assertInternalLinkType_547871e (): InternalLinkType? = null

// Success
// UserAlreadyParticipant
// UserPrivacyRestricted
// UserWasBanned
@Autogenerated fun assertInviteGroupCallParticipantResult_d4d7f840 (): InviteGroupCallParticipantResult? = null

// BasicGroup
// Channel
// Supergroup
@Autogenerated fun assertInviteLinkChatType_5c8a8927 (): InviteLinkChatType? = null

// Array
// Boolean
// Null
// Number
// Object
// String
@Autogenerated fun assertJsonValue_fe9bf6a4 (): JsonValue? = null

// RequestChat
// RequestLocation
// RequestPhoneNumber
// RequestPoll
// RequestUsers
// Text
// WebApp
@Autogenerated fun assertKeyboardButtonType_b955a01e (): KeyboardButtonType? = null

// Deleted
// Ordinary
// Pluralized
@Autogenerated fun assertLanguagePackStringValue_11536986 (): LanguagePackStringValue? = null

// Photo
// Video
@Autogenerated fun assertLinkPreviewAlbumMedia_8c33c943 (): LinkPreviewAlbumMedia? = null

// Album
// Animation
// App
// Article
// Audio
// Background
// ChannelBoost
// Chat
// Document
// EmbeddedAnimationPlayer
// EmbeddedAudioPlayer
// EmbeddedVideoPlayer
// ExternalAudio
// ExternalVideo
// GroupCall
// Invoice
// Message
// Photo
// PremiumGiftCode
// ShareableChatFolder
// Sticker
// StickerSet
// Story
// SupergroupBoost
// Theme
// Unsupported
// UpgradedGift
// User
// Video
// VideoChat
// VideoNote
// VoiceNote
// WebApp
@Autogenerated fun assertLinkPreviewType_e3ce10d5 (): LinkPreviewType? = null

// Default
// Empty
// File
@Autogenerated fun assertLogStream_924d9e8f (): LogStream? = null

// Open
// RequestConfirmation
@Autogenerated fun assertLoginUrlInfo_7af29c11 (): LoginUrlInfo? = null

// Chin
// Eyes
// Forehead
// Mouth
@Autogenerated fun assertMaskPoint_40914d4e (): MaskPoint? = null

// MessageAnimatedEmoji
// MessageAnimation
// MessageAudio
// MessageBasicGroupChatCreate
// MessageBotWriteAccessAllowed
// MessageCall
// MessageChatAddMembers
// MessageChatBoost
// MessageChatChangePhoto
// MessageChatChangeTitle
// MessageChatDeleteMember
// MessageChatDeletePhoto
// MessageChatJoinByLink
// MessageChatJoinByRequest
// MessageChatSetBackground
// MessageChatSetMessageAutoDeleteTime
// MessageChatSetTheme
// MessageChatShared
// MessageChatUpgradeFrom
// MessageChatUpgradeTo
// MessageContact
// MessageContactRegistered
// MessageCustomServiceAction
// MessageDice
// MessageDocument
// MessageExpiredPhoto
// MessageExpiredVideo
// MessageExpiredVideoNote
// MessageExpiredVoiceNote
// MessageForumTopicCreated
// MessageForumTopicEdited
// MessageForumTopicIsClosedToggled
// MessageForumTopicIsHiddenToggled
// MessageGame
// MessageGameScore
// MessageGift
// MessageGiftedPremium
// MessageGiftedStars
// MessageGiveaway
// MessageGiveawayCompleted
// MessageGiveawayCreated
// MessageGiveawayPrizeStars
// MessageGiveawayWinners
// MessageGroupCall
// MessageInviteVideoChatParticipants
// MessageInvoice
// MessageLocation
// MessagePaidMedia
// MessagePaidMessagePriceChanged
// MessagePaidMessagesRefunded
// MessagePassportDataReceived
// MessagePassportDataSent
// MessagePaymentRefunded
// MessagePaymentSuccessful
// MessagePaymentSuccessfulBot
// MessagePhoto
// MessagePinMessage
// MessagePoll
// MessagePremiumGiftCode
// MessageProximityAlertTriggered
// MessageRefundedUpgradedGift
// MessageScreenshotTaken
// MessageSticker
// MessageStory
// MessageSuggestProfilePhoto
// MessageSupergroupChatCreate
// MessageText
// MessageUnsupported
// MessageUpgradedGift
// MessageUsersShared
// MessageVenue
// MessageVideo
// MessageVideoChatEnded
// MessageVideoChatScheduled
// MessageVideoChatStarted
// MessageVideoNote
// MessageVoiceNote
// MessageWebAppDataReceived
// MessageWebAppDataSent
@Autogenerated fun assertMessageContent_235cea4f (): MessageContent? = null

// EmojiReaction
// PremiumSticker
@Autogenerated fun assertMessageEffectType_7a4e2342 (): MessageEffectType? = null

// Group
// Private
// Unknown
@Autogenerated fun assertMessageFileType_79d01776 (): MessageFileType? = null

// Channel
// Chat
// HiddenUser
// User
@Autogenerated fun assertMessageOrigin_f2224a59 (): MessageOrigin? = null

// MyPrivacyRestricted
// Read
// TooOld
// Unread
// UserPrivacyRestricted
@Autogenerated fun assertMessageReadDate_5a6e5fbf (): MessageReadDate? = null

// Message
// Story
@Autogenerated fun assertMessageReplyTo_699c5345 (): MessageReplyTo? = null

// SendAtDate
// SendWhenOnline
// SendWhenVideoProcessed
@Autogenerated fun assertMessageSchedulingState_ce8fe50d (): MessageSchedulingState? = null

// Immediately
// Timer
@Autogenerated fun assertMessageSelfDestructType_58882d8c (): MessageSelfDestructType? = null

// Chat
// User
@Autogenerated fun assertMessageSender_439d4c9c (): MessageSender? = null

// Failed
// Pending
@Autogenerated fun assertMessageSendingState_90c81bfe (): MessageSendingState? = null

// ChatEventLog
// ChatHistory
// ChatList
// ForumTopicHistory
// HistoryPreview
// MessageThreadHistory
// Notification
// Other
// Screenshot
// Search
@Autogenerated fun assertMessageSource_eeb3e95 (): MessageSource? = null

// Call
// File
@Autogenerated fun assertNetworkStatisticsEntry_187c867b (): NetworkStatisticsEntry? = null

// Mobile
// MobileRoaming
// None
// Other
// WiFi
@Autogenerated fun assertNetworkType_6cd85444 (): NetworkType? = null

// Calls
// Mentions
// Messages
// SecretChat
@Autogenerated fun assertNotificationGroupType_afec32af (): NotificationGroupType? = null

// ChannelChats
// GroupChats
// PrivateChats
@Autogenerated fun assertNotificationSettingsScope_edff9c28 (): NotificationSettingsScope? = null

// NewCall
// NewMessage
// NewPushMessage
// NewSecretChat
@Autogenerated fun assertNotificationType_dd6d967f (): NotificationType? = null

// Boolean
// Empty
// Integer
// String
@Autogenerated fun assertOptionValue_710db1a4 (): OptionValue? = null

// Anchor
// Animation
// Audio
// AuthorDate
// BlockQuote
// ChatLink
// Collage
// Cover
// Details
// Divider
// Embedded
// EmbeddedPost
// Footer
// Header
// Kicker
// List
// Map
// Paragraph
// Photo
// Preformatted
// PullQuote
// RelatedArticles
// Slideshow
// Subheader
// Subtitle
// Table
// Title
// Video
// VoiceNote
@Autogenerated fun assertPageBlock_b923b80b (): PageBlock? = null

// Center
// Left
// Right
@Autogenerated fun assertPageBlockHorizontalAlignment_c0d442f9 (): PageBlockHorizontalAlignment? = null

// Bottom
// Middle
// Top
@Autogenerated fun assertPageBlockVerticalAlignment_1d620a05 (): PageBlockVerticalAlignment? = null

// Photo
// Preview
// Unsupported
// Video
@Autogenerated fun assertPaidMedia_a2956719 (): PaidMedia? = null

// Anonymous
// Chat
// Regular
@Autogenerated fun assertPaidReactionType_fef36429 (): PaidReactionType? = null

// Address
// BankStatement
// DriverLicense
// EmailAddress
// IdentityCard
// InternalPassport
// Passport
// PassportRegistration
// PersonalDetails
// PhoneNumber
// RentalAgreement
// TemporaryRegistration
// UtilityBill
@Autogenerated fun assertPassportElement_ed3ed69e (): PassportElement? = null

// DataField
// File
// Files
// FrontSide
// ReverseSide
// Selfie
// TranslationFile
// TranslationFiles
// Unspecified
@Autogenerated fun assertPassportElementErrorSource_10220502 (): PassportElementErrorSource? = null

// Address
// BankStatement
// DriverLicense
// EmailAddress
// IdentityCard
// InternalPassport
// Passport
// PassportRegistration
// PersonalDetails
// PhoneNumber
// RentalAgreement
// TemporaryRegistration
// UtilityBill
@Autogenerated fun assertPassportElementType_fe25158a (): PassportElementType? = null

// Regular
// StarSubscription
// Stars
@Autogenerated fun assertPaymentFormType_23df0e49 (): PaymentFormType? = null

// Other
// SmartGlocal
// Stripe
@Autogenerated fun assertPaymentProvider_cba7114d (): PaymentProvider? = null

// Regular
// Stars
@Autogenerated fun assertPaymentReceiptType_5891a75e (): PaymentReceiptType? = null

// Change
// ConfirmOwnership
// Verify
@Autogenerated fun assertPhoneNumberCodeType_ee762ba6 (): PhoneNumberCodeType? = null

// Quiz
// Regular
@Autogenerated fun assertPollType_324514f9 (): PollType? = null

// AccentColor
// AdvancedChatManagement
// AnimatedProfilePhoto
// AppIcons
// BackgroundForBoth
// Business
// ChatBoost
// CustomEmoji
// DisabledAds
// EmojiStatus
// ForumTopicIcon
// ImprovedDownloadSpeed
// IncreasedLimits
// IncreasedUploadFileSize
// LastSeenTimes
// MessageEffects
// MessagePrivacy
// ProfileBadge
// RealTimeChatTranslation
// SavedMessagesTags
// UniqueReactions
// UniqueStickers
// UpgradedStories
// VoiceRecognition
@Autogenerated fun assertPremiumFeature_f73f45af (): PremiumFeature? = null

// ActiveStoryCount
// BioLength
// CaptionLength
// ChatFolderChosenChatCount
// ChatFolderCount
// ChatFolderInviteLinkCount
// CreatedPublicChatCount
// FavoriteStickerCount
// MonthlyPostedStoryCount
// PinnedArchivedChatCount
// PinnedChatCount
// PinnedSavedMessagesTopicCount
// SavedAnimationCount
// ShareableChatFolderCount
// SimilarChatCount
// StoryCaptionLength
// StorySuggestedReactionAreaCount
// SupergroupCount
// WeeklyPostedStoryCount
@Autogenerated fun assertPremiumLimitType_6d916432 (): PremiumLimitType? = null

// BusinessFeature
// Feature
// LimitExceeded
// Link
// Settings
// StoryFeature
@Autogenerated fun assertPremiumSource_daf37913 (): PremiumSource? = null

// CustomExpirationDuration
// LinksAndFormatting
// PermanentViewsHistory
// PriorityOrder
// SaveStories
// StealthMode
// VideoQuality
@Autogenerated fun assertPremiumStoryFeature_17d0292c (): PremiumStoryFeature? = null

// Http
// Mtproto
// Socks5
@Autogenerated fun assertProxyType_bc1a1076 (): ProxyType? = null

// HasUsername
// IsLocationBased
@Autogenerated fun assertPublicChatType_fc36b3cf (): PublicChatType? = null

// Message
// Story
@Autogenerated fun assertPublicForward_dc496684 (): PublicForward? = null

// Animation
// Audio
// BasicGroupChatCreate
// ChatAddMembers
// ChatChangePhoto
// ChatChangeTitle
// ChatDeleteMember
// ChatJoinByLink
// ChatJoinByRequest
// ChatSetBackground
// ChatSetTheme
// Contact
// ContactRegistered
// Document
// Game
// GameScore
// Gift
// Giveaway
// Hidden
// InviteVideoChatParticipants
// Invoice
// Location
// MediaAlbum
// MessageForwards
// PaidMedia
// Photo
// Poll
// PremiumGiftCode
// ProximityAlertTriggered
// RecurringPayment
// ScreenshotTaken
// Sticker
// Story
// SuggestProfilePhoto
// Text
// UpgradedGift
// Video
// VideoChatEnded
// VideoChatStarted
// VideoNote
// VoiceNote
@Autogenerated fun assertPushMessageContent_6685917b (): PushMessageContent? = null

// All
// Contacts
// None
@Autogenerated fun assertReactionNotificationSource_9173268f (): ReactionNotificationSource? = null

// CustomEmoji
// Emoji
// Paid
@Autogenerated fun assertReactionType_43844388 (): ReactionType? = null

// AnonymousAdministrator
// Guest
@Autogenerated fun assertReactionUnavailabilityReason_bd270bcb (): ReactionUnavailabilityReason? = null

// ForceReply
// InlineKeyboard
// RemoveKeyboard
// ShowKeyboard
@Autogenerated fun assertReplyMarkup_d6ebcdbe (): ReplyMarkup? = null

// MessagesRequired
// Ok
// OptionRequired
// TextRequired
@Autogenerated fun assertReportChatResult_63f241a6 (): ReportChatResult? = null

// ChildAbuse
// Copyright
// Custom
// Fake
// IllegalDrugs
// PersonalDetails
// Pornography
// Spam
// UnrelatedLocation
// Violence
@Autogenerated fun assertReportReason_cf03e541 (): ReportReason? = null

// AdsHidden
// Failed
// Ok
// OptionRequired
// PremiumRequired
@Autogenerated fun assertReportSponsoredResult_79c7a88e (): ReportSponsoredResult? = null

// Ok
// OptionRequired
// TextRequired
@Autogenerated fun assertReportStoryResult_f48b5654 (): ReportStoryResult? = null

// UserRequest
// VerificationFailed
@Autogenerated fun assertResendCodeReason_43b67e0c (): ResendCodeReason? = null

// Declined
// Ok
// Pending
@Autogenerated fun assertResetPasswordResult_7d1022f2 (): ResetPasswordResult? = null

// Failed
// Pending
// Succeeded
@Autogenerated fun assertRevenueWithdrawalState_c7736b7b (): RevenueWithdrawalState? = null

// Anchor
// AnchorLink
// Bold
// EmailAddress
// Fixed
// Icon
// Italic
// Marked
// PhoneNumber
// Plain
// Reference
// Strikethrough
// Subscript
// Superscript
// Underline
// Url
// s
@Autogenerated fun assertRichText_58eb3f54 (): RichText? = null

// AuthorHidden
// MyNotes
// SavedFromChat
@Autogenerated fun assertSavedMessagesTopicType_7aafbb6f (): SavedMessagesTopicType? = null

// Channel
// Group
// Private
@Autogenerated fun assertSearchMessagesChatTypeFilter_64401152 (): SearchMessagesChatTypeFilter? = null

// Animation
// Audio
// ChatPhoto
// Document
// Empty
// FailedToSend
// Mention
// Photo
// PhotoAndVideo
// Pinned
// UnreadMention
// UnreadReaction
// Url
// Video
// VideoNote
// VoiceAndVideoNote
// VoiceNote
@Autogenerated fun assertSearchMessagesFilter_f22b2582 (): SearchMessagesFilter? = null

// Closed
// Pending
// Ready
@Autogenerated fun assertSecretChatState_f028091e (): SecretChatState? = null

// Regular
// Upgraded
@Autogenerated fun assertSentGift_cad35baf (): SentGift? = null

// Android
// Apple
// Brave
// Chrome
// Edge
// Firefox
// Ipad
// Iphone
// Linux
// Mac
// Opera
// Safari
// Ubuntu
// Unknown
// Vivaldi
// Windows
// Xbox
@Autogenerated fun assertSessionType_c099cac6 (): SessionType? = null

// Error
// Pending
// Text
@Autogenerated fun assertSpeechRecognitionResult_537e9541 (): SpeechRecognitionResult? = null

// Bot
// Channel
@Autogenerated fun assertStarSubscriptionType_5f8c3fdb (): StarSubscriptionType? = null

// Incoming
// Outgoing
@Autogenerated fun assertStarTransactionDirection_b34a8067 (): StarTransactionDirection? = null

// AffiliateProgramCommission
// AppStoreDeposit
// BotInvoicePurchase
// BotInvoiceSale
// BotPaidMediaPurchase
// BotPaidMediaSale
// BotSubscriptionPurchase
// BotSubscriptionSale
// BusinessBotTransferReceive
// BusinessBotTransferSend
// ChannelPaidMediaPurchase
// ChannelPaidMediaSale
// ChannelPaidReactionReceive
// ChannelPaidReactionSend
// ChannelSubscriptionPurchase
// ChannelSubscriptionSale
// FragmentDeposit
// FragmentWithdrawal
// GiftPurchase
// GiftSale
// GiftTransfer
// GiftUpgrade
// GiveawayDeposit
// GooglePlayDeposit
// PaidMessageReceive
// PaidMessageSend
// PremiumBotDeposit
// PremiumPurchase
// TelegramAdsWithdrawal
// TelegramApiUsage
// Unsupported
// UpgradedGiftPurchase
// UpgradedGiftSale
// UserDeposit
@Autogenerated fun assertStarTransactionType_cc7db86 (): StarTransactionType? = null

// Async
// Data
// Error
@Autogenerated fun assertStatisticalGraph_2332b901 (): StatisticalGraph? = null

// Tgs
// Webm
// Webp
@Autogenerated fun assertStickerFormat_4fea4648 (): StickerFormat? = null

// CustomEmoji
// Mask
// Regular
@Autogenerated fun assertStickerFullType_466eed9d (): StickerFullType? = null

// CustomEmoji
// Mask
// Regular
@Autogenerated fun assertStickerType_cc811bb7 (): StickerType? = null

// GiftedStars
// PremiumGift
// PremiumGiftCodes
// PremiumGiveaway
// PremiumSubscription
// StarGiveaway
// Stars
@Autogenerated fun assertStorePaymentPurpose_7d6676bd (): StorePaymentPurpose? = null

// AppStore
// GooglePlay
@Autogenerated fun assertStoreTransaction_3818b01a (): StoreTransaction? = null

// Link
// Location
// Message
// SuggestedReaction
// UpgradedGift
// Venue
// Weather
@Autogenerated fun assertStoryAreaType_1dc15b8a (): StoryAreaType? = null

// Photo
// Unsupported
// Video
@Autogenerated fun assertStoryContent_c5cd7a63 (): StoryContent? = null

// Forward
// Repost
// View
@Autogenerated fun assertStoryInteractionType_ef03003e (): StoryInteractionType? = null

// Archive
// Main
@Autogenerated fun assertStoryList_cf1e963 (): StoryList? = null

// HiddenUser
// PublicStory
@Autogenerated fun assertStoryOrigin_e44a8fca (): StoryOrigin? = null

// CloseFriends
// Contacts
// Everyone
// SelectedUsers
@Autogenerated fun assertStoryPrivacySettings_77d8fbd3 (): StoryPrivacySettings? = null

// CheckPassword
// CheckPhoneNumber
// ConvertToBroadcastGroup
// Custom
// EnableArchiveAndMuteNewChats
// ExtendPremium
// ExtendStarSubscriptions
// GiftPremiumForChristmas
// RestorePremium
// SetBirthdate
// SetPassword
// SetProfilePhoto
// SubscribeToAnnualPremium
// UpgradePremium
// ViewChecksHint
@Autogenerated fun assertSuggestedAction_c92fb71c (): SuggestedAction? = null

// Administrators
// Banned
// Bots
// Contacts
// Mention
// Recent
// Restricted
// Search
@Autogenerated fun assertSupergroupMembersFilter_e70c061b (): SupergroupMembersFilter? = null

// ChatInvite
// StickerSet
// Supergroup
// User
@Autogenerated fun assertTMeUrlType_38521396 (): TMeUrlType? = null

// Chosen
// Current
// InternalLink
@Autogenerated fun assertTargetChat_75ff347c (): TargetChat? = null

// GiftedStars
// JoinChat
// PremiumGift
// PremiumGiftCodes
// PremiumGiveaway
// StarGiveaway
// Stars
@Autogenerated fun assertTelegramPaymentPurpose_cdfb4e9e (): TelegramPaymentPurpose? = null

// BankCardNumber
// BlockQuote
// Bold
// BotCommand
// Cashtag
// Code
// CustomEmoji
// EmailAddress
// ExpandableBlockQuote
// Hashtag
// Italic
// MediaTimestamp
// Mention
// MentionName
// PhoneNumber
// Pre
// PreCode
// Spoiler
// Strikethrough
// TextUrl
// Underline
// Url
@Autogenerated fun assertTextEntityType_56c1e709 (): TextEntityType? = null

// HTML
// Markdown
@Autogenerated fun assertTextParseMode_ef88df13 (): TextParseMode? = null

// Gif
// Jpeg
// Mpeg4
// Png
// Tgs
// Webm
// Webp
@Autogenerated fun assertThumbnailFormat_bf2b0de0 (): ThumbnailFormat? = null

// Bots
// Calls
// Channels
// ForwardChats
// Groups
// InlineBots
// Users
// WebAppBots
@Autogenerated fun assertTopChatCategory_2b3d1ad7 (): TopChatCategory? = null

// AccentColors
// ActiveEmojiReactions
// ActiveLiveLocationMessages
// ActiveNotifications
// AnimatedEmojiMessageClicked
// AnimationSearchParameters
// ApplicationRecaptchaVerificationRequired
// ApplicationVerificationRequired
// AttachmentMenuBots
// AuthorizationState
// AutosaveSettings
// AvailableMessageEffects
// BasicGroup
// BasicGroupFullInfo
// BusinessConnection
// BusinessMessageEdited
// BusinessMessagesDeleted
// Call
// ChatAccentColors
// ChatAction
// ChatActionBar
// ChatActiveStories
// ChatAddedToList
// ChatAvailableReactions
// ChatBackground
// ChatBlockList
// ChatBoost
// ChatBusinessBotManageBar
// ChatDefaultDisableNotification
// ChatDraftMessage
// ChatEmojiStatus
// ChatFolders
// ChatHasProtectedContent
// ChatHasScheduledMessages
// ChatIsMarkedAsUnread
// ChatIsTranslatable
// ChatLastMessage
// ChatMember
// ChatMessageAutoDeleteTime
// ChatMessageSender
// ChatNotificationSettings
// ChatOnlineMemberCount
// ChatPendingJoinRequests
// ChatPermissions
// ChatPhoto
// ChatPosition
// ChatReadInbox
// ChatReadOutbox
// ChatRemovedFromList
// ChatReplyMarkup
// ChatRevenueAmount
// ChatTheme
// ChatThemes
// ChatTitle
// ChatUnreadMentionCount
// ChatUnreadReactionCount
// ChatVideoChat
// ChatViewAsTopics
// ConnectionState
// ContactCloseBirthdays
// DefaultBackground
// DefaultPaidReactionType
// DefaultReactionType
// DeleteMessages
// DiceEmojis
// FavoriteStickers
// File
// FileAddedToDownloads
// FileDownload
// FileDownloads
// FileGenerationStart
// FileGenerationStop
// FileRemovedFromDownloads
// ForumTopic
// ForumTopicInfo
// FreezeState
// GroupCall
// GroupCallParticipant
// GroupCallParticipants
// GroupCallVerificationState
// HavePendingNotifications
// InstalledStickerSets
// LanguagePackStrings
// MessageContent
// MessageContentOpened
// MessageEdited
// MessageFactCheck
// MessageInteractionInfo
// MessageIsPinned
// MessageLiveLocationViewed
// MessageMentionRead
// MessageReaction
// MessageReactions
// MessageSendAcknowledged
// MessageSendFailed
// MessageSendSucceeded
// MessageUnreadReactions
// NewBusinessCallbackQuery
// NewBusinessMessage
// NewCallSignalingData
// NewCallbackQuery
// NewChat
// NewChatJoinRequest
// NewChosenInlineResult
// NewCustomEvent
// NewCustomQuery
// NewInlineCallbackQuery
// NewInlineQuery
// NewMessage
// NewPreCheckoutQuery
// NewShippingQuery
// Notification
// NotificationGroup
// Option
// OwnedStarCount
// PaidMediaPurchased
// Poll
// PollAnswer
// ProfileAccentColors
// QuickReplyShortcut
// QuickReplyShortcutDeleted
// QuickReplyShortcutMessages
// QuickReplyShortcuts
// ReactionNotificationSettings
// RecentStickers
// SavedAnimations
// SavedMessagesTags
// SavedMessagesTopic
// SavedMessagesTopicCount
// SavedNotificationSounds
// ScopeNotificationSettings
// SecretChat
// ServiceNotification
// SpeechRecognitionTrial
// SpeedLimitNotification
// StarRevenueStatus
// StickerSet
// Story
// StoryDeleted
// StoryListChatCount
// StoryPostFailed
// StoryPostSucceeded
// StoryStealthMode
// SuggestedActions
// Supergroup
// SupergroupFullInfo
// TermsOfService
// TrendingStickerSets
// UnconfirmedSession
// UnreadChatCount
// UnreadMessageCount
// User
// UserFullInfo
// UserPrivacySettingRules
// UserStatus
// VideoPublished
// WebAppMessageSent
@Autogenerated fun assertUpdate_b40eb8d7 (): Update? = null

// Backdrop
// Model
// Symbol
@Autogenerated fun assertUpgradedGiftAttributeId_ddb04f12 (): UpgradedGiftAttributeId? = null

// AllowCalls
// AllowChatInvites
// AllowFindingByPhoneNumber
// AllowPeerToPeerCalls
// AllowPrivateVoiceAndVideoNoteMessages
// AllowUnpaidMessages
// AutosaveGifts
// ShowBio
// ShowBirthdate
// ShowLinkInForwardedMessages
// ShowPhoneNumber
// ShowProfilePhoto
// ShowStatus
@Autogenerated fun assertUserPrivacySetting_6bbb3d7e (): UserPrivacySetting? = null

// AllowAll
// AllowBots
// AllowChatMembers
// AllowContacts
// AllowPremiumUsers
// AllowUsers
// RestrictAll
// RestrictBots
// RestrictChatMembers
// RestrictContacts
// RestrictUsers
@Autogenerated fun assertUserPrivacySettingRule_58b21786 (): UserPrivacySettingRule? = null

// Empty
// LastMonth
// LastWeek
// Offline
// Online
// Recently
@Autogenerated fun assertUserStatus_6492acaf (): UserStatus? = null

// Bot
// Deleted
// Regular
// Unknown
@Autogenerated fun assertUserType_233bc6f4 (): UserType? = null

// CubicBezierCurve
// Line
@Autogenerated fun assertVectorPathCommand_4e60caf3 (): VectorPathCommand? = null

// Compact
// FullScreen
// FullSize
@Autogenerated fun assertWebAppOpenMode_b354c84f (): WebAppOpenMode? = null